### ISSUE TITLE
[BUG] Everything is a GIF

### ISSUE THREAD

**Issue by rakosi2** [Tharki-God/LegalDiscordBypasses#1]
When Discord loses focus, It will mark GIFs with the text "GIF" to the upper left.

LegalDiscordBypasses will mark all images with the GIF label on focus lost. Even with all of the settings of LDB disabled. This does not happen when LDB is disabled.

Edit: should mention that I am on LDB 1.0.4 and Replugged v4.5.2

**Comment by lunarythia** [comment]
You beat me on reporting this bug by one minute.

**Comment by lunarythia** [comment]
> When Discord loses focus, It will mark GIFs with the text "GIF" to the upper left.
> 
> LegalDiscordBypasses will mark all images with the GIF label on focus lost. Even with all of the settings of LDB disabled. This does not happen when LDB is disabled.
> 
> Edit: should mention that I am on LDB 1.0.4 and Replugged v4.5.2

I will also add to this, that another consequence of this is that the “Favourite” button (which usually shows up for GIFs) also shows up for any image you hover over.

**Comment by yofukashino** [comment]
okay I shouldn't Happen when all settings disabled but this is supposed to be an feature

**Comment by yofukashino** [comment]
nvm you actually need an restart after disabling that setting

**Comment by yofukashino** [comment]
wait I forgot to add an switch for that
will be added in next update.
it's an feature tho

**Comment by rakosi2** [comment]
If you are going to edit this, are you able to add the file extension instead of just saying "GIF" ?

**Comment by yofukashino** [comment]
> If you are going to edit this, are you able to add the file extension instead of just saying "GIF" ?

fuck I edited your comment instead of reply. anyway I will try

**Comment by lunarythia** [comment]
> wait I forgot to add an switch for that will be added in next update. it's an feature tho

Ohh, I see, lol.

**Comment by yofukashino** [comment]
done fixed
