### ISSUE TITLE
Idle patch prevents discord from sending push notifications to Mobile

### ISSUE THREAD

**Issue by Diyagi** [Tharki-God/LegalDiscordBypasses#2]
The idle patch in this plugin works as intended and prevents discord from noticing that the user is AFK.
That said it seems to also prevent discord from switching on the mobile push notifications after the time in the configuration has passed,
I dont really care about the idle patch but theres no on/off switch for it, is it possible to implement it ?

**Comment by yofukashino** [comment]
if you want push notifications than disable the idle patch. you wouldn't get notifications until you are idle or offline. other option is to close discord on idle. you can setup some script for that

**Comment by Diyagi** [comment]
> I dont really care about the idle patch but theres no on/off switch for it, is it possible to implement it ?

**Comment by yofukashino** [comment]
> > I dont really care about the idle patch but theres no on/off switch for it, is it possible to implement it ?
> 
> 

there is one in settings of plugin ig

**Comment by yofukashino** [comment]
nvm I have somehow made it use the same button as client themes. you can turn that off for the meanwhile and I will fix that soon too

**Comment by yofukashino** [comment]
fixed in latest release
