### ISSUE TITLE
Spotify listen along dont work fine

### ISSUE THREAD

**Issue by Ren0X1** [Tharki-God/LegalDiscordBypasses#3]
with the new update spotify listen along option has stopped working and does not function as it should
![image](https://github.com/Tharki-God/LegalDiscordBypasses/assets/34504445/7ec32337-87ff-4efa-aa7e-cca959c49c66)

**Comment by yofukashino** [comment]
seems to work fine for me. seems like skill issue. not even listen along issue

**Comment by Ren0X1** [comment]
sure

**Comment by yofukashino** [comment]
yup its a Spotify pause issue and it works fine for me just update your plugin??
